### ISSUE TITLE
ResStock v3.0.0 Release Checklist

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#829]
- [x] Create a release branch
  - [x] Update `CHANGELOG.md` (especially for #443)
  - [x] Bump version (`resources/buildstock.rb`)
  - [x] Merge into `develop`
- [x] Merge `develop` into `main`
- [x] Create release (tag on `main`)

**Comment by afontani** [comment]
We release ResStock with OpenStudio-HPXML v1.5.

**Comment by afontani** [comment]
@joseph-robertson : Suggest changing this to ResStock v3.0

**Comment by joseph-robertson** [comment]
https://github.com/NREL/resstock/tree/v3.0.0
